feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
]

feed/models.py
from django.contrib.auth.models import User
from django.db import models

class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    
    def __str__(self):
        return self.text[0:100]

followers/models.py
from django.db import models
from django.contrib.auth.models import User

class Follower(models.Model):
    followed_by = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        related_name = 'followed_by'
    )
    following = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        related_name = 'following'
    )

    def __str__(self):
        return f"{self.followed_by.id} is following {self.following.id}"

    class Meta:
        unique_together = ('followed_by', 'following',)

profiles/models.py
from django.contrib.auth.models import User 
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


class Profiles(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
        
    )
    image = ImageField(upload_to='profiles')

    def __str__(self):
        return self.user.username
        
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django User is created."""
    if created:
        Profiles.objects.create(user=instance)
    

feed/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from followers.models import Follower
from .models import Post

class HomePage(TemplateView):
    http_method_names = ['get']
    template_name = "feed/homepage.html"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated:
            following = list(
                Follower.objects.filter(followed_by=self.request.user).values_list('following', flat=True)
            )
            if not following:
                # show the default 30
                posts = Post.objects.all().order_by('-id')[0:30]
            else:
                posts = Post.objects.filter(author__in=following).order_by('-id')[0:60]
        else:
            posts = Post.objects.all().order_by('-id')[0:30]
        context['posts'] = posts
        return context 
   
class PostDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "feed/detail.html"
    model = Post
    context_object_name = "post"


class CreateNewPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "feed/create.html"
    fields = ['text']
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        post = Post.objects.create(
            text = request.POST.get('text'),
            author = request.user,
        )

        return render(
            request,
            "includes/post.html",
            {
                "post": post,
                "show_detail_link": True,
            },
            content_type = "application/html"
        )

followers/views.py
from django.shortcuts import render

# Create your views here.

profiles/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseBadRequest, JsonResponse
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from feed.models import Post
from followers.models import Follower

class ProfileDetailView(DetailView):
    http_method_name = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user" 
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context ['total_posts'] = Post.objects.filter(author = user).count()
        context ['total_followers'] = Post.objects.filter(author = user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context

class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username = data ['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == "follow":
            follower, created = Follower.objects.get_or_create(
                followed_by = request.user,
                following = other_user
            )
        else: 
            
            try:
                follower = Follower.objects.get(
                    followed_by = request.user,
                    following = other_user,
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

            return JsonResponse({
                'success' : True,
                'wording': "Unfollow" if data['action'] == "follow" else "Follow"
            })

feed/templates/feed/create.html
{% extends "base.html" %}

{% block title %}Create a new post{% endblock %}

{% block body %}
    <form method="POST" action=".">
    {% csrf_token %}
    {{form.as_p}}
    <div>
        <div class="my-3">
            <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
                <span class="mr-2">Create Post</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
            </button>
        </div>
    </div>
</form>
{% endblock %}

feed/templates/feed/detail.html
{% extends "base.html" %}

{% block title %}{{ post.text }} by {{ post.author.username }}{% endblock %}

{% block body %} 
    {% include "includes/post.html" with post=post %}
{% endblock %} 

feed/templates/feed/homepage.html
{% extends "base.html" %}

{% block title %}Changed the title of the homepage{% endblock %}

{% block body %}
    <div id="posts-container">
    {% for post in posts %}
        {% include "includes/post.html" with post=post show_detail_link=True %}
    {% endfor %}
    </div>
{% endblock %}

profiles/templates/profiles/detail.html
{% extends "base.html" %} 

{% load thumbnail %} 

{% block title %}{{ user.username}}{% endblock title %} 

{% block body %}
<div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
  <img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
  <div class="flex justify-center -mt-8">
    {% thumbnail user.profile.image "100x100" crop="center" as im %}
    <img
      src="{{ im.url }}"
      class="rounded-full border-solid border-white border-2 -mt-3"
    />
    {% endthumbnail %}
  </div>
  <div class="text-center px-3 pb-6 pt-2 text-lg">
    <h3 class="text-black text-sm bold font-sans">{{ user.username }}</h3>
    {% if request.user.is_authenticated %}
        {% if request.user != user %}
    <div class="mt-3">
      <button
        class="bg-white text-gray-800 font-bold rounded border-b-2 
        border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white 
        shadow-md py-1 px-3 inline-flex items-center js-follow"
        data-username="{{ user.username }}"
        data-action="{% if you_follow %}un{% endif %}follow"
        data-url="{% url 'profiles:follow' user.username %}"
        type="button"
      >
        <span class="mr-2 text-sm js-follow-text">
            {% if you_follow %}
                Unfollow
            {% else %}
                Follow
            {% endif %}
        </span>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
        >
          <path
            fill="currentcolor"
            d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"
          ></path>
        </svg>
      </button>
    </div>
    {% endif %}
    {% else %}
    <div class="mt-3 text-sm">login to follow the user</div>
    {% endif %}
  </div>
  <div class="flex justify-center pb-3 text-grey-dark">
    <div class="text-center mr-3 border-r pr-3">
      <h2>{{ total_posts }}</h2>
      <span>Posts</span>
    </div>
    <div class="text-center">
      <h2>{{total_followers}}</h2>
      <span>Followers</span>
    </div>
  </div>
</div>
{% endblock body %}